### ISSUE TITLE
요구사항 명세서 작성에 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by hyou55** [SMU-EB0055/SE2021_HAEA0008_2#12]
1. DB에 저장한다는 내용을 정상 흐름에 넣을지 사후 조건에 넣는 것이 맞는지.
 - 대안 흐름으로 '사용자가 내용 등록을 취소한다'는 내용이 있을 때, 사후 조건은 정상  흐름 뿐만 아니라 대안 흐름에서도 최종적으로 실행되어야 하는 조건이기 때문에 시스템이 DB에 내용을 저장한다. 라는 조건은 대안 흐름의 사후 조건이 아니게 되므로 정상 흐름에 넣어야 하는 문장인가요?
 
2. 로그인 조건을 사전 조건에 넣는 것이 맞는지.
 - 액터가 업주일 때 모든 사전 조건에 업주가 로그인한 상태이다. 가 들어가야 하나요?
 -아니면 업주라는 액터가 업주계정으로 로그인한 상태를 포함하고 있기 때문에 생략해도 되는 부분인가요?
  
3. 정상 흐름에서 
 - 1. 체크인/체크아웃 날짜 및 시간, 예약 번호, 예약자 이름, 휴대폰 번호, 총 결제금액을  입력받는다.
 - 2. 예약 관련 정보 항목을 입력 받는다.
 둘 중에 1번은 세부적인 사항인가요? 그렇다면 2번으로 작성하는 것이 맞나요?

**Comment by JongdaeHan** [comment]
1. 사후조건은 유즈케이스에서 어떤 일이 일어나든 그 유즈케이스 후의 시스템 상태를 나타냅니다. 따라서 정상 흐름에 넣는 것이 맞습니다.
2. 사전조건에 입력하는 것이 맞습니다. 그래야 이후에 개발자들이 업주용 페이지를 개발시 업주의 로그인 여부를 확인하겠지요?
3. 네 2번이 맞습니다. 해당 내용이 중요하고 다른 유즈케이스에서도 사용한다면, 주석이나 데이터 딕셔너리 형태로 해당 내용을 따로 적기도 합니다만 유즈케이스 명세 내에는 적지 않는 것이 좋습니다.(how에 해당)

**Comment by hyou55** [comment]
넵! 정말 감사합니다!!
