### ISSUE TITLE
계획서 작성과 관련해서 질문사항이 있습니다.

### ISSUE THREAD

**Issue by hyou55** [SMU-EB0055/SE2021_HAEA0008_2#15]
**1.**  WBS에서 수업에서 작성 되어야 할 모든 산출물을 아직 배우지 못했는데 예상되는 단위 작업을 적고 변하는 것에 따라 수정하는 부분을 어떻게 이해하는 것이 좋을까요?

> ex1)  예를 들어서 수업을 기준으로 패키지를 나눠서( 요구 사항 분석, 프로젝트 계획, 설계, 코딩, 테스트, 최종 문서 작성) 이렇게 작성하는 것인지

> ex2) 실제로 기업에서 하는 프로젝트라고 생각하고 (요구 사항 분석, 프로젝트 계획, 개발, 배포, 사이트 관리) 이렇게 나눠야 하는 것인지 궁금합니다.
   
만약에 ex2와 같은 경우로 작성해야 한다면 프로젝트 중간 중간 계획서를 확인하면서, 계획대로 진행되고 있는지 아닌지 계속 업데이트 해야 한다고 하셨는데, 실제 수업 내용에서 진행되지 않는 작업들(배포, 사이트 관리)에 대한 확인은 이후에 어떻게 해야 하나요?

**2.** 패키지를 나눌 때 '하나의 작업 패키지 단위'가 '하나의 문서(산출물)'로 작성되는 것을 기준으로 하지 않고, '여러 개의 패키지'를 묶어서 '하나의 문서(산출물)'가 작성이 가능하다는 것을 기준으로 해도 괜찮은가요?

> ex1) 게시판 글 확인, 작성, 삭제 같은 경우를 '게시판 구현'이라는 하나의 패키지로만 표현 하는 경우

> ex2) 로그인, 회원가입, 비밀번호 찾기, 아이디 찾기, 확인 등의 기능을 '로그인 구현'이라는 하나의 패키지로 묶는 경우

 위에 예시와 같은 경우로 '게시판 구현', '로그인 구현'이라는 패키지를 WBS에 적어도 되나요?

아니면 위와 같은 경우도 작은 단위이기 때문에 모든 기능의 구현을 '기능 설계 및 구현'이라는 하나의 패키지 단위로 묶어서 작성 하는 것이 맞는 건가요?

그렇다면 기능 설계 구현 아래에 ( 상세 설계서, 기능 구현 이미지, 기능 검토 결과서, 구현 소스코드) 이렇게만 적는 것이 맞나요?

**3.**  사후조건에 추가할 만한 예시가 있을까요? 없다면 비워두어도 괜찮을까요?

요구사항 명세서의 사후 조건이 유즈케이스에서 어떤 일이 일어나든 그 유즈케이스 후의 시스템의 상태를 나타낸다고 하셨는데, 

> ex1) 화면을 표시한다, 로그인 된다는 것은 시스템의 상태를 나타내는 것이 아니기 때문에  

> ex2) 게시글 작성 등의 결과로 db에 내용이 저장되는 것은 대안 흐름에서 게시글 작성이 취소될 수 있기 때문에,
  위에 두 상황이 각각 사후 조건에 맞지 않는다면 사후 조건에 들어갈 만한 내용이 어떤 것이 있는지 알 수 있을까요?

**Comment by JongdaeHan** [comment]
확인이 늦었네요. 메일을 못 봤어요. ㅠㅠ
1. ex1과 같이, 실제 우리가 할 일을 기준으로 작업을 계획하시면 됩니다.
2. 정확하게는 비밀번호 찾기와 같은 작업은 하나의 패키지로 보기 어려울 정도로 작습니다. 로그인 기능 구현 정도가 하나의 작업 패키지 단위가 되겠네요. 약 1인의 개발자가 2주간 개발할 분량이라고 보시면 대충 맞습니다.  모든 기능 구현을 하나의 패키지로 묶는 것은 너무 큰 단위구요.
3. '사용자가 로그인 된다'도 시스템의 현재 상태가 변화한 상태라고 보시면 됩니다. '예약 취소' 유즈케이스의 사후 조건은 사용자가 메인 페이지로 이동된다와 같을 수 있겠죠.

**Comment by hyou55** [comment]
확인했습니다! 감사합니다:)
