### ISSUE TITLE
프로젝트 계획서 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by Cinema-Paradiso** [SMU-EB0055/SE2021_HAEA0008_2#16]
프로젝트 계획서을 작성하던 중 헷갈리는 부분이 있어서 질문 드립니다.
계획서 내용 중 5. 위험 관리 계획을 서술하기 위한 지식은 아직 배우지 않은건가요?
감사합니다.

**Comment by JongdaeHan** [comment]
네 그렇습니다. 


-----------------------------
HAN, JONG DAE
Assistant Professor, Department of Computer Science
College of Computer Software and Media Technology, Sangmyung University
20, HONGIMUN 2-GIL, JONGNO-GU,SEOUL 110-743, KOREA
Phone : +82-10-8928-1213
***@***.***

**Comment by Cinema-Paradiso** [comment]
감사합니다
