### ISSUE TITLE
요구사항 명세서 작성 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by hyou55** [SMU-EB0055/SE2021_HAEA0008_2#2]
안녕하세요 교수님. 요구사항 명세서 작성 중에 가장 먼저 나오는 변경 이력에 대해서 질문이 있습니다.

변경 이력은 4월 9일 과제 제출을 완료한 이후에 명세서 수정이 이루어졌을 때 적는 항목인가요

아니면 자체적인 최종 결정에서 내용이 변경 될 때마다 수정 사항을 적는 것인가요?

**Comment by JongdaeHan** [comment]
자체적으로 변경이 이루어질때마다 그 내용을 기록하시면 됩니다.
