### ISSUE TITLE
요구사항 명세서 작성 관련해서 질문 드립니다.

### ISSUE THREAD

**Issue by Jeeseob** [SMU-EB0055/SE2021_HAEA0008_2#3]
안녕하세요 교수님.
저희가 요구사항 명세서 작성을 하다보니 아직 구현 여부가 정확하지 않아서 어려움이 있습니다.
아무래도 제안요청서가 애매하여 사용자 입장에서 생각하다보니 아이디어로 떠오르는 기능들은 많은데 저희가 아직 많이 부족하고 개발 시간도 한학기 정도여서 몇몇 아이디어로 떠오른 기능들은 구현이 어려울 것 같습니다. 요구사항 명세서 작성시 저희 수준에서 구현을 염두에 두고 작성을 해야하는지 아니면 현재 기술로 개발가능한지 여부만 판단해서 작성하면 되는지 궁금합니다.

**Comment by JongdaeHan** [comment]
직접 구현하신다고 생각하시고 작성하셔야 합니다. 구현을 못하게 되더라도, 구현을 못할 제품 범위라면 설계도 어려울 거에요.
