### ISSUE TITLE
명세서 제출일자와 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by hyou55** [SMU-EB0055/SE2021_HAEA0008_2#7]
명세서 제출일인 4월 9일이 4월 9일 23시 59분인가요 아니면 4월 8일 23시 59분인가요?
그리고 명세서는 수정 할 때 마다 업데이트 하라고 하셨는데 평가는 4월 9일까지 제출된 문서로 평가가 이루어지는지도 궁금합니다.

**Comment by JongdaeHan** [comment]
4월 9일 23시 59분입니다. 
평가는 둘 다입니다. 4월 9분 시점에서의 문서를 제가 한번 아카이빙해두고, 최종 평가시에 전체 변경 이력을 포함한 최종 버전으로 한번 더 평가합니다.

**Comment by hyou55** [comment]
네 감사합니다!
