### ISSUE TITLE
화면기술과 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by hyou55** [SMU-EB0055/SE2021_HAEA0008_2#8]
웹으로 구현을 한다는 가정 하에서 
1. 마우스 커서를 글씨 위에 올렸을 때 글씨가 두껍게 변하는 것
2. 버튼을 클릭 했을 때 시스템에서 띄우는 내용을 입력하는 입력창 
3. "내용이 없습니다." 라는 메시지의 팝업 창
4. 버튼 위에 커서를 올렸을 때 버튼의 모양이 바뀌는 것
5.  내비게이션 바가 어느 화면에서도 표시된다.
위의 5가지는 화면 기술인가요? 웹 상에서 화면 기술이 어떤 것인지 잘 모르겠습니다..

**Comment by JongdaeHan** [comment]
화면 설명이 맞기는 한데요, 얘들은 너무 디테일하네요. 요구사항에서 how는 쓰지 않는다고 했지요? 

일단 정답은 없습니다만 저라면 

> 마우스 커서를 글씨 위에 올렸을 때 글씨가 두껍게 변하는 것 

대신

> 필요한 내용을 강조

정도로 두겠습니다. 2,3,4도 입력창/팝업창이 있다는 정도만 그려두고, 지금 하신 고민은 설계 및 구현 단계에서 고민하겠습니다.
단 5번같은 내용은 명확하게 필요한 화면 기술이겠네요.

**Comment by hyou55** [comment]
네 감사합니다!
